### ISSUE TITLE
Node v22 `punycode` deprecation notice via `node-fetch`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-fetch#42]
```
(node:61059) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:113:7)
    at Module._load (node:internal/modules/cjs/loader:1053:17)
    at Module.require (node:internal/modules/cjs/loader:1290:19)
    at require (node:internal/modules/helpers:188:18)
    at Object.<anonymous> (/Users/zachleat/Code/eleventy-base-blog/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1455:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
```

Upgrade `node-fetch` to new 3.0 ESM version?

**Comment by zachleat** [comment]
Fixed by #37.

**Comment by uncenter** [comment]
Seeing as https://github.com/11ty/eleventy-fetch/milestone/5 is complete will we see an update soon? Would love to get rid of this deprecation warning and we've had a few questions about it in the Discord as well.

**Comment by zachleat** [comment]
Good callout @uncenter—trying to get v3 core shipped this week to minimize Node versioning issues

**Comment by uncenter** [comment]
FYI still getting the the warning because @11ty/eleventy-img depends on the older version - once @11ty/eleventy-fetch@v5 releases maybe a patch release for @11ty/eleventy-img to upgrade the dependency?

**Comment by zachleat** [comment]
yeah, absolutely. We’ll bump eleventy-img after this stabilizes—seems like this would be a major release given that the options passed to `fetch` via `cacheOptions.fetchOptions` might be different? Though not explicitly o the docs here: https://www.11ty.dev/docs/plugins/image/#advanced-caching-options-for-remote-images it’s on the fetch docs here: https://www.11ty.dev/docs/plugins/fetch/#fetch-google-fonts-css
